server:
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when-authorized

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: changeme
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 60000
    requested-heartbeat: 60
    template:
      retry:
        enabled: true
        initial-interval: 2000
        max-attempts: 3
        max-interval: 10000
        multiplier: 2
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 3
          max-interval: 10000
        default-requeue-rejected: false
        auto-startup: true
        acknowledge-mode: auto
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

integration:
  mockoon:
    base-url: http://localhost:3000/api/v3

security:
  jwt:
    secretKey: e6d0e2f583c349aaa24b780183bfde7aa136a556ad0230232b889683ec56e846
    expirationTimeInMillis: 900000 # 15 minutes in milliseconds
    issuer: https://svaskevicius.lt

cache:
  entries:
    user_data: 900
    video_statistics: 300
